[functions.calculate-shipping]
verify_jwt = false

[functions.delivery-tracker-webhook]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.book-shiprocket-shipment]
verify_jwt = false

[functions.sms-hook]
verify_jwt = false
